http/src/util/service/handler.rs

This may be a hacky solution, so I understand if this get rejected for maintainability considerations. However I tried to add comments for the workarounds used here.

borrowed extractors

---

http/src/util/service/handler.rs
http/src/util/service/handler_impl.rs
web/src/extract/body.rs
web/src/extract/extension.rs
web/src/extract/header.rs
web/src/extract/json.rs
web/src/extract/mod.rs
web/src/extract/path.rs
web/src/extract/request.rs
web/src/extract/state.rs
web/src/extract/uri.rs
web/src/response.rs

a subset of #173 that would still be necessary even after the TAIT regression is fixed.

future-proof handler traits

---

http/src/util/service/context_priv.rs
http/src/util/service/handler.rs
http/src/util/service/mod.rs
http/src/util/service/route.rs
http/src/util/service/router_priv.rs
web/src/app/mod.rs
web/src/error.rs
web/src/handler/impls.rs

Rework `Responder` trait to take `Req` instead of `&mut Req`.
Add new type for `matchit::MatchError`.

do not expose matchit::MatchError in router mod.

---

postgres/src/client.rs
postgres/src/connect.rs
postgres/src/io/buffered_io.rs
postgres/src/io/context.rs
postgres/src/lib.rs
postgres/src/request.rs

due to a rare race condition in async array.

revert #256

---

http-encoding/src/coder.rs
http-encoding/src/decode.rs
http-encoding/src/encode.rs
http-encoding/src/error.rs
http-encoding/src/lib.rs
http/src/body.rs
web/src/app/mod.rs
web/src/handler/impls.rs
web/src/middleware/compress.rs
web/src/middleware/decompress.rs
web/src/response.rs

Add default error handler for App.

re-work http-encoding error types.

---

client/Cargo.toml
client/src/response.rs
http/src/body.rs
http/src/error.rs
test/tests/h1.rs
web/Cargo.toml
web/src/handler/types/websocket.rs

Instead of a type alias. This enables easy constructor for it.

make StreamBody type a concreate type.

---

server/src/server/mod.rs

making it easier to catch build time error from tokio crate.

move tokio runtime builder before spawn thread.

---

server/src/builder.rs
server/src/server/mod.rs
server/src/server/service.rs

rename BuildServiceSync trait to BuildServiceFn.

---

client/src/pool.rs

increase idle client connection timeout from 60 to 600 seconds.

increase time out of idle client connection.

---

client/src/body.rs
client/src/h1/proto/dispatcher.rs
client/src/h1/proto/encode.rs
http/src/h1/proto/dispatcher.rs
http/src/h1/proto/encode.rs
http/src/response.rs

Context::encode_head take in &B instead of BodySize.

inline bodysize check to http1 Context api.

---

http/Cargo.toml
http/src/util/service/router_priv.rs

remove `MatchError::is_trailing_slash`. add `MatchError::missing_trailing_slash` and `MatchError::extra_trailing_slash`

update matchit dep. rework match error api.

---

http/src/h2/proto/headers.rs
http/src/h2/proto/hpack/mod.rs
http/src/h2/proto/mod.rs
http/src/h2/proto/priority.rs
http/src/h2/proto/settings.rs
test/tests/h2_v2.rs
unsafe_collection/src/bytes/byte_str.rs

add dummy test for `xitca_http::h2::run`

add http2 headers parsing.

---

http/src/error.rs
http/src/h1/error.rs
http/src/h2/proto/headers.rs
http/src/h2/proto/settings.rs
web/src/middleware/mod.rs

reexport logger middleware in web.

---

.github/workflows/ci.yml
.github/workflows/clippy-fmt.yml
README.md

enabling language feature like `let else` to be used as stable.

update nightly compiler requirement to 2022-11-03

---

examples/file/src/main.rs
http/src/util/service/route.rs

from
```rust
Route::new(fn_service(..)).methods([Method::GET,..])
```
to
```rust
Route::new([Method::GET,..]).route(fn_service(..))
```

rework Route service.

---

postgres/src/error.rs
router/src/params.rs
router/src/tree.rs
router/tests/tree.rs
unsafe_collection/src/lib.rs
unsafe_collection/src/small_str.rs
unsafe_collection/src/uninit.rs

Add SmallBoxedStr to store small sized param value on stack. Remove inlined Params variant.

improve router perf.

---

examples/websocket/src/main.rs
http-ws/Cargo.toml
http-ws/src/lib.rs
http-ws/src/stream.rs
web/Cargo.toml
web/src/handler/types/websocket.rs

add shortcut methods for sending text/binary message.

dont expose tokio channel type.

---

postgres/src/config.rs
postgres/src/io/buffered.rs
postgres/src/io/context.rs
postgres/src/lib.rs
postgres/src/prepare.rs
postgres/src/response.rs

no_std is a goal for xitca-postgres.

use core and alloc when possible.

---

http-ws/src/lib.rs
http-ws/src/stream.rs
service/src/object.rs
service/src/service/function.rs
web/src/handler/types/websocket.rs

rename `EncodeStream` to `RequestStream`
rename `DecodeStream` and `DecodeSender` to `ResponseStream` and `ResponseSender`
rename `DecodeStream::encode_stream` method to `DecodeStream::response_stream`
rename `EncodeError` to `WsError`

rework http-ws stream feature.

---

codegen/Cargo.toml
codegen/src/lib.rs
postgres/src/transport/tcp.rs

also reduce dns look up times when multiple ports is given for single host.

update to syn 2.0

---

.cargo/config.toml
examples/io-uring/Cargo.toml
examples/io-uring/src/main.rs
http/Cargo.toml
http/src/builder.rs
http/src/h1/builder.rs
http/src/h1/dispatcher_uring.rs
http/src/h1/service.rs
http/src/tls/mod.rs
http/src/tls/rustls_uring.rs
io/Cargo.toml
io/src/io_uring.rs
io/src/lib.rs
io/src/net.rs
io/src/net/io_uring.rs
server/src/builder.rs
tls/Cargo.toml
tls/src/lib.rs
tls/src/rustls_uring.rs

add `HttpServiceBuilder::io_uring` api for enabling http/1 with io-uring. 
add `HttpServiceBuilder::rustls_uring` api for enabling http/1 tls with io-uring.

add AsyncBufRead/Write traits.

---

Cargo.toml
postgres/Cargo.toml

update quinn to 0.11

---

http/src/util/service/context_priv.rs
http/src/util/service/router_priv.rs
service/src/object.rs
service/src/service/ext.rs
web/src/app/mod.rs
web/src/app/object.rs
web/src/service/tower_http_compat.rs

and move Argument and Request generic type to the trait itself.

rename ObjectConstructor trait.

---

client/Cargo.toml
client/src/h1/body.rs
client/src/h1/proto/dispatcher.rs
client/src/request.rs

at the cost of perf: an extra memory copy of body.

drop dep of tokio-util and tokio/io-util.

---

.github/workflows/ci.yml
README.md
http/src/util/service/router_priv.rs

fix rustc warning when compiling "xitca_http/util-service" feature.

update compiler requirement.

---

examples/grpc/src/main.rs
examples/io-uring/src/main.rs
examples/multi-http-services/src/main.rs
http/src/builder.rs
http/src/error.rs
http/src/h1/builder.rs
http/src/h2/builder.rs
http/src/h3/builder.rs
test/src/lib.rs
web/src/server.rs

switch from `HttpServiceBuilder::new(service)` to `service.enclosed(HttpServiceBuilder::new())` style of API.

make HttpServiceBuilder middleware.

---

http/src/util/service/handler.rs
web/src/handler/impls.rs
web/src/handler/types/body.rs
web/src/handler/types/extension.rs
web/src/handler/types/header.rs
web/src/handler/types/json.rs
web/src/handler/types/multipart.rs
web/src/handler/types/params.rs
web/src/handler/types/path.rs
web/src/handler/types/query.rs
web/src/handler/types/request.rs
web/src/handler/types/state.rs
web/src/handler/types/string.rs
web/src/handler/types/uri.rs
web/src/handler/types/vec.rs
web/src/handler/types/websocket.rs
web/src/middleware/compress.rs
web/src/middleware/decompress.rs
web/src/middleware/eraser.rs
web/src/middleware/limit.rs
web/src/service/tower_http_compat.rs

 simplify FromRequest trait lifetime params.

---

client/Cargo.toml
examples/compression/Cargo.toml
examples/grpc/Cargo.toml
examples/multi-http-services/Cargo.toml
examples/multipart/Cargo.toml
examples/websocket/Cargo.toml
examples/websocket/src/main.rs
http-ws/Cargo.toml
http/Cargo.toml
postgres/Cargo.toml
server/Cargo.toml
web/src/handler/types/websocket.rs

unbox certain websocket callbacks from public api.

---

http/src/body.rs
http/src/http.rs
http/src/util/middleware/context_priv.rs
http/src/util/middleware/extension.rs
web/src/body.rs
web/src/middleware/compress.rs

make Compress middleware more generic over input.

---

web/src/middleware/eraser.rs

restore `TypeEraser::request_body` and correctly map error type to `xitca_web::error::Error` with `TypeErase::error`.

fix TypeEraser middleware.

---

client/Cargo.toml
client/src/builder.rs
client/src/h3/proto/dispatcher.rs
client/src/tls/connector.rs
examples/io-uring/Cargo.toml
examples/io-uring/src/main.rs
http/Cargo.toml
http/src/h3/proto/dispatcher.rs
http/src/tls/rustls.rs
http/src/tls/rustls_uring.rs
postgres/Cargo.toml
postgres/src/driver/quic.rs
postgres/src/driver/raw/tls.rs
postgres/src/driver/tls.rs
postgres/src/lib.rs
postgres/src/proxy.rs
tls/Cargo.toml
tls/src/rustls.rs
web/Cargo.toml

rustls 0.22.

---

client/src/builder.rs
client/src/lib.rs

Fix tests not passing on some documentation code block

fix(client): fix tests on documentation

---

client/src/builder.rs
client/src/pool/exclusive.rs

It keeps current default configuration to not change behavior, however it may be better to reduce it
As an example nginx will, by default, induce a 75 sec keep alive duration

feat(client): allow to configure keep alive duration for http1 exclusive pool

---

client/src/client.rs

Related to this PR https://github.com/HFQR/xitca-web/pull/1210

fix(upgrade): fix documentation on how to use upgrade api

---

.github/workflows/ci.yml
io/src/net.rs
server/src/builder.rs
server/src/net/mod.rs
server/src/server/service.rs
server/src/worker/mod.rs

Listen(Dyn) traits look like more fitting to `xitca-server` crate. 
@joelwurtz What's your opinion on this change?

move listen traits from io to server

---

web/src/handler/types/header.rs

https://github.com/HFQR/xitca-web/discussions/1223

Add extractor for HeaderMap

---

http-encoding/src/encode.rs

There should be no transfer encoding header on h2 (and h3), it currently bug when having compression and http2 (see https://github.com/hyperium/h2/blob/master/src/proto/streams/send.rs#L82)

fix(encode): do not set chunked transfer encoding if http2 or more

---

client/src/h1/proto/dispatcher.rs

I'm not sure i understand why it try to read the response if body cannot be send.
In our case this was causing the client to be "lock" after some times : 
* We receive request with body on our server
* We forward the body to the client (without reading the body since we don't need / want to buffer the whole body into the server, we simply forward)
* The client close / cancel the request during sending the body
* An error happens when sending the body (connection close)
* The backend is still waiting for the body to send the response (connection is not closed)
* We hit the request timeout 
I assume if there is an error when sending the body we should just throw the error, in most cases, even if the backend send a response, it will be an error as something bad happen.

fix(client): return error if cannot send request body
