http/src/util/service/handler.rs

remove free lifetime in handler service

---

http/src/util/service/handler.rs
web/src/app/mod.rs
web/src/response.rs

HRTB reject any lifetime bounds on the quantified type.
```rust
trait Trait<T> {}
impl<'a, T> Trait<&'a T> for ()
where
T: 'a // this bound, though always correct, is unnecessary and invalidates the HRTB `(): for<'a> Trait<&'a u8>`
{}
```
We need to always make use of implicit bounds.
For this reason, the lifetime bound on `Responder::Future` and `Handler::Future` were removed. This way the borrow checker will infer the lifetime of the future to be the minimum lifetime of all the trait input type paramters, which is correct for these traits.

fix hrtb for Handler and Responder

---

http/src/util/service/handler.rs
service/src/async_closure.rs
service/src/factory/enclosed_fn.rs
service/src/factory/ext.rs
service/src/ready/enclosed_fn.rs
service/src/service/enclosed_fn.rs

Explicit lifetime bounds on AsyncClosure can be problematic when used with HRTB.

Fix ICE and simplify EnclosedFn2

---

http/src/util/service/context.rs
service/src/factory/and_then.rs
service/src/factory/ext.rs
service/src/factory/map.rs
service/src/pipeline/pipeline_enum.rs
service/src/ready/and_then.rs
service/src/ready/map.rs
service/src/ready/map_err.rs
service/src/service/and_then.rs
service/src/service/map.rs

Keep `ServiceFactoryExt::map/map_err/and_then` combinators in line with `std::result::Result`.

narrow AndThen pipe service's error type.

---

http-codegen/src/lib.rs
http/src/h1/service.rs
http/src/h2/service.rs
http/src/h3/service.rs
http/src/service.rs
http/src/util/service/context.rs
http/src/util/service/route.rs
http/src/util/service/router.rs
server/src/worker/mod.rs
service/src/ready/and_then.rs
service/src/ready/enclosed_fn.rs
service/src/ready/function.rs
service/src/ready/map_err.rs
service/src/ready/mod.rs
test/tests/macro.rs
web/src/app/mod.rs

rework `ReadyService::Ready` type. It does not force to output Result<T, E> from the `ready` method.

rework ReadyService trait.

---

examples/io-uring.rs
examples/websocket.rs
http/src/util/service/context.rs
web/src/app/mod.rs
web/src/app/object.rs
web/src/handler/impls.rs
web/src/handler/types/body.rs
web/src/handler/types/extension.rs
web/src/handler/types/header.rs
web/src/handler/types/html.rs
web/src/handler/types/json.rs
web/src/handler/types/path.rs
web/src/handler/types/request.rs
web/src/handler/types/state.rs
web/src/handler/types/uri.rs
web/src/request.rs

ContexService would pass `Context<'_, Req, C>` to it's child service.
`WebRequest` is made to a copy type and pass to web services as copied value instead of as `&mut WebRequest`.

ContextService pass owned typed to downstream.

---

http/src/util/service/handler.rs
http/src/util/service/route.rs
web/src/app/mod.rs

Don't require `Req` to be inferred in `hander_service` and `Ruote` methods.

web: fix state inference problem

---

http/src/util/service/handler.rs

remove Handler trait

---

server/src/builder.rs
test/src/lib.rs
web/src/server.rs

xitca_server::ServerBuilder::{listen, listen_unix} becomes infallible.

simplify Server::listen apis.

---

client/src/error.rs

Inherient `http::uri::InvalidUri` type to `xitca_client::error::InvalidUri`'s `Other` variant.

rework xitca_client::error::InvalidUri error.

---

http-file/src/chunk.rs
http-file/src/error.rs
http-file/src/lib.rs
http-file/src/runtime.rs
http/src/h2/proto/headers.rs

`ServeDir::serve` would attach `content-length` header automatically and no manual insertion after return needed anymore.

add head method support to http-file.

---

postgres/Cargo.toml
postgres/src/client.rs
postgres/src/io/buffered_io.rs
postgres/src/io/context.rs
postgres/src/prepare.rs
postgres/src/query.rs
postgres/src/statement.rs

due to lack of AsyncDrop a bounded async channel would have trouble to cancel prepared statement with drop guard. use unbounded channel instead. 
client would not be able to handle backlog with naive unbounded channel and this issue would be addressed in the future.

use unbounded channel for postgres client.

---

examples/file/src/main.rs
http/src/body.rs
http/src/h1/proto/encode.rs
test/tests/h1.rs
web/src/app/mod.rs
web/src/body.rs
web/src/handler/impls.rs
web/src/handler/types/body.rs
web/src/handler/types/extension.rs
web/src/handler/types/header.rs
web/src/handler/types/json.rs
web/src/handler/types/multipart.rs
web/src/handler/types/params.rs
web/src/handler/types/path.rs
web/src/handler/types/query.rs
web/src/handler/types/request.rs
web/src/handler/types/state.rs
web/src/handler/types/string.rs
web/src/handler/types/uri.rs
web/src/handler/types/vec.rs
web/src/handler/types/websocket.rs
web/src/lib.rs
web/src/middleware/compress.rs
web/src/middleware/decompress.rs
web/src/middleware/eraser.rs
web/src/middleware/limit.rs
web/src/request.rs
web/src/response.rs

`xitca_web::stream` module has been renamed to `xitca_web::body`.
rename `xitca_web::WebStream` trait to `BodyStream`.
move `xitca_web::request::RequestBody` and `xitca_web::response::ResponseBody` to `xitca_web::body` module.
rename `xitca_http::body::StreamBody` to `BoxStream`.

rework body module and naming.

---

client/src/h1/proto/dispatcher.rs
http/src/config.rs
http/src/h1/dispatcher.rs
http/src/h1/error.rs
http/src/h1/proto/context.rs
http/src/h1/proto/decode.rs
http/src/h1/proto/encode.rs
http/src/h1/service.rs
http/src/service.rs
http/src/util/hint.rs
http/src/util/mod.rs
http/src/util/timer.rs
test/src/lib.rs
web/src/server.rs

`xitca_http::confg::HttpServiceConfig::first_request_timeout` is renamed to `request_head_timeout`.
`xitca_web::HttpServer::first_request_timeout` is renamed accordingly.
Instead of handling only the first request timeout this api is able to handle all request timeout now.

experiment new behavior of consistent request timeout handling.

---

http/src/util/service/context_priv.rs
http/src/util/service/mod.rs
http/src/util/service/router_priv.rs
service/src/object.rs
service/src/service/ext.rs
web/src/app/mod.rs
web/src/app/object.rs

The usage of `IntoObject` will be narrowed down to only usable for storing object safe `Service` type in `Router`.
In exchange specialized `ServiceObject` type can be infered from it's Request type removing the need for `Router::with_custom_object` API(and it's constructor type).

move IntoObject trait to xitca_http::util::service::router.

---

examples/cloudflare-worker/Cargo.toml
examples/grpc/Cargo.toml
examples/io-uring/Cargo.toml
http/Cargo.toml
http/src/http.rs
http/src/util/mod.rs
http/src/util/service/context_priv.rs
http/src/util/service/handler.rs
http/src/util/service/mod.rs
web/Cargo.toml

Of all the util services only router depend on extra dependency. This PR enable all util services by default and make router service an optional feature.

narrow util-service feature down to router.

---

http/src/util/middleware/context_priv.rs
http/src/util/service/mod.rs
http/src/util/service/router_priv.rs
web/src/app/mod.rs
web/src/app/object.rs
web/src/middleware/decompress.rs

This enables router to be a `Send` and `Sync` constructor type with the help of `Router::insert_sync` API.
the default Router construction is still `!Send` and `!Sync` in `xitca-http` and the default App construction is forced to be `Send` and `Sync` in `xitca-web`.

add marker type to IntoObject trait.

---

examples/compression/src/main.rs
examples/file/src/main.rs
examples/hello-world/src/main.rs
examples/multipart/src/main.rs
examples/sync/src/main.rs
examples/tower-http/src/main.rs
examples/unix/src/main.rs
examples/wasi/src/main.rs
examples/websocket/src/main.rs
http/src/util/middleware/context_priv.rs
http/src/util/service/router_priv.rs
service/src/object.rs
service/src/service/mod.rs
web/src/app/mod.rs
web/src/app/object.rs
web/src/handler/mod.rs
web/src/handler/types/state.rs
web/src/lib.rs
web/src/middleware/tower_http_compat.rs
web/src/server.rs

Introducing `HttpServer::serve` API for directly accept an App instance when constructing the application.
Remove `HttpServer::new` and `App::new_current_thread_state` API.

remove using of function closure in HttpServer.

---

examples/grpc/src/main.rs
examples/io-uring/src/main.rs
examples/multi-http-services/src/main.rs
http/src/builder.rs
http/src/lib.rs
http/src/util/middleware/context_priv.rs
http/src/util/service/mod.rs
http/src/util/service/router_priv.rs
server/src/builder.rs
server/src/lib.rs
server/src/server/future.rs
server/src/server/mod.rs
server/src/server/service.rs
service/src/service/function.rs
test/src/lib.rs
test/tests/h1.rs
test/tests/h2.rs
test/tests/h2_v2.rs
test/tests/h3.rs
test/tests/websocket.rs
web/src/app/mod.rs
web/src/app/object.rs
web/src/server.rs

further remove closure usage. xitca_server::Builder::bind_xxx and listen_xxx APIs now accept thread safe types bound to `Send` and `Sync` directly.
revert `xitca_http::ulti::service::router::IntoObject` trait change to not include marker type anymore. remove `Router::insert_sync` API and make `Router` only accept `Send` + `Sync` routes in all cases. In other word `Router` is always forced to be thread safe from now on.
update examples to reflex these changes.

remove closure from xitca_server::Builder.

---

examples/cloudflare-worker/src/lib.rs
http/src/util/service/mod.rs
http/src/util/service/route.rs
http/src/util/service/router_priv.rs
web/src/error.rs
web/src/handler/impls.rs

remove `xitca_http::util::service::route::RouteError` and move it's variant into `xitca_http::util::service::router::RouterError`.
This change enables `Router` to accept `fn_service` and `get(fn_service)` at the same time without special error conversion.

rework RouterError.

---

examples/multipart/src/main.rs
http/src/body.rs
http/src/h1/proto/encode.rs
test/tests/h1.rs
web/Cargo.toml
web/src/app/mod.rs
web/src/body.rs
web/src/error.rs
web/src/handler/error.rs
web/src/handler/impls.rs
web/src/handler/types/body.rs
web/src/handler/types/extension.rs
web/src/handler/types/header.rs
web/src/handler/types/json.rs
web/src/handler/types/multipart.rs
web/src/handler/types/params.rs
web/src/handler/types/path.rs
web/src/handler/types/query.rs
web/src/handler/types/request.rs
web/src/handler/types/state.rs
web/src/handler/types/string.rs
web/src/handler/types/uri.rs
web/src/handler/types/vec.rs
web/src/handler/types/websocket.rs
web/src/middleware/decompress.rs
web/src/middleware/limit.rs

rename `xitca_http::body::BoxStream` to `BoxBody`.
add `xitca_web::error::Error` type for type erase error handling. all extractors now return Error<C>.
replace `Responder` trait with `Service` trait for error generation.

rework xitca_web error type v2.

---

codegen/src/lib.rs
examples/multi-http-services/src/main.rs
http/src/builder.rs
http/src/h1/builder.rs
http/src/h2/builder.rs
http/src/h3/builder.rs
http/src/util/middleware/context_priv.rs
http/src/util/middleware/extension.rs
http/src/util/middleware/logger.rs
http/src/util/middleware/socket_config.rs
service/src/middleware/unchecked_ready.rs
service/src/service/enclosed.rs
service/src/service/ext.rs
service/src/service/function.rs
service/src/service/opt.rs
test/tests/macro.rs
web/src/app/mod.rs
web/src/middleware/compress.rs
web/src/middleware/decompress.rs
web/src/middleware/eraser.rs
web/src/middleware/limit.rs
web/src/middleware/sync.rs
web/src/middleware/tower_http_compat.rs
web/src/server.rs

`ServiceExt::enclosed` now accept a type impl `Service<Result<S, E>>`. This enables middleware handling inner service builder's error type inside it's `Service::call` method. 
Before:
```rust
impl<S> Service<S> for Mw {
async fn call(&self, service: S) -> Result<Self::Response, Self::Error> {
// know nothing about the error path of producing S 
}
}
Router::new()
.insert("/", fn_service(...))
.insert("/", fn_service(...).enclosed(Mw))  // this line can easily fail due to Mw don't know the proper error type.
```
Now:
```rust
impl<Result<S, E>> Service<Result<S, E>> for Mw {
async fn call(&self, res: Result<S, E>) -> Result<Self::Response, Self::Error> {
// mw is able to handle inner service builder error with E type.
}
}
Router::new()
.insert("/", fn_service(...))
.insert("/", …
```

rework middleware.

---

examples/Cargo.toml
examples/error-handle/Cargo.toml
examples/error-handle/src/main.rs
examples/file/src/main.rs
examples/multipart/src/main.rs
examples/sync/src/main.rs
http/src/util/service/handler.rs
web/src/handler/impls.rs
web/src/handler/sync.rs
web/src/handler/types/html.rs
web/src/handler/types/json.rs
web/src/handler/types/multipart.rs
web/src/handler/types/vec.rs
web/src/handler/types/websocket.rs

`Responder` trait now output `Result<Response, Error>` type. The associate `Responder::Error` type would be converted to `FromRequest::Error` utilizing `From` trait. This would help reducing nesting of output type where a `Result<Result<_, Responder::Error>, FromRequest::Error>` can be converted to `Result<_, FromRequest::Error>` with `impl From<Responder::Error> for FromRequest::Error`.
add example for xitca-web error handling.

rework handler_service's error handling.

---

examples/multi-http-services/src/main.rs
service/src/lib.rs
service/src/middleware/group.rs
service/src/middleware/mod.rs
service/src/service/function.rs
service/src/service/mod.rs

remove `xitca_service::fn_build_nop` and `Group` would take it's role. For better naming and module placement.

add Group middleware.

---

examples/macros/src/main.rs
http/src/body.rs
web/src/app/mod.rs
web/src/handler/types/multipart.rs
web/src/handler/types/state.rs
web/src/middleware/decompress.rs
web/src/middleware/limit.rs
web/src/middleware/mod.rs
web/src/middleware/tower_http_compat.rs

Instead of accepting generic B: Stream type as request body. `App` now always expect `xitca_web::body::RequestBody` type.
For testing purpose all request body type must be convert to `RequestBody` before passing to app service. 
Multiple `From` trait implement has been added to ease this process.

use concrete request body type for App.

---

codegen/src/route.rs
examples/error-handle/src/main.rs
examples/macros/src/main.rs
web/src/app/mod.rs
web/src/middleware/decompress.rs
web/src/middleware/eraser.rs
web/src/middleware/limit.rs

Besides rare use case `WebContext<'_, C, B>` can most time be simplified to `WebContext<'_, C>`.

remove generic B type from route macro and examples.

---

client/src/error.rs
client/src/h1/error.rs
examples/error-handle/src/main.rs
examples/grpc/src/main.rs
examples/multipart/src/main.rs
http-encoding/src/coder.rs
http-encoding/src/error.rs
http-multipart/src/content_disposition.rs
http-multipart/src/error.rs
http-multipart/src/field.rs
http-multipart/src/header.rs
http-multipart/src/lib.rs
http/src/body.rs
http/src/error.rs
http/src/h2/error.rs
http/src/h3/error.rs
web/src/body.rs
web/src/error.rs
web/src/handler/types/json.rs
web/src/handler/types/multipart.rs
web/src/handler/types/vec.rs
web/src/middleware/eraser.rs
web/src/middleware/limit.rs

remove typed `BodyError`. all body related error type are type alias of `Box<dyn std::error::Error + Send + Sync>`

rework stream body type.

---

http/src/body.rs
web/src/app/mod.rs
web/src/body.rs
web/src/middleware/compress.rs
web/src/middleware/tower_http_compat.rs
web/src/service/tower_http_compat.rs

`xitca_web::error::Error` does not drop streaming response body anymore. therefore streaming error to client is fixed.

fix error service handling.

---

http/src/util/service/router_priv.rs
service/src/lib.rs
service/src/pipeline/mod.rs
web/src/app/mod.rs

Rename `Pipeline<_, _, marker::_>` from `<marker>ServiceFactory` to `<marker>Builder`. add export of `Pipeline<_, _, marker::BuildMap>`

service type alias renaming

---

http/src/util/service/handler.rs
web/src/error.rs
web/src/handler/impls.rs
web/src/handler/sync.rs
web/src/handler/types/html.rs
web/src/handler/types/json.rs
web/src/handler/types/vec.rs
web/src/handler/types/websocket.rs

rename `Responder::respond_to` to `Responder::respond`.
add `Responder::map`.
impl `Responder` for tuple types upto 6 items. The first item in tuple would call `Responder::respond` to generate a base response type and following items would call `Responder::map` and mutate it base on their trait method implementations.

rework Responder trait.

---

http/src/h1/proto/codec.rs
http/src/h1/proto/decode.rs

but at the same strict rules on duplicate `content-length` and `transfer-encoding: chunked` headers.

relax chunked encoding decode.

---

client/src/builder.rs
client/src/client.rs
client/src/lib.rs
client/src/tls/connector.rs

remove `TlsConnect` trait and use `Service` trait for custom tls connector. See `ClientBuilder::tls_connector` for example.

rework client tls connector.

---

client/Cargo.toml
client/src/h1/body.rs
client/src/h1/proto/dispatcher.rs
client/src/service.rs

Restore behavior of efficient http1 body reading.

import tokio-util for buffered read.

---

client/Cargo.toml
client/src/builder.rs
client/src/client.rs
client/src/connection.rs
client/src/error.rs
client/src/h1/body.rs
client/src/h1/proto/dispatcher.rs
client/src/h2/proto/dispatcher.rs
client/src/http_tunnel.rs
client/src/lib.rs
client/src/tls/connector.rs
client/src/tls/stream.rs
client/src/ws.rs
http/CHANGES.md
http/Cargo.toml
http/src/tls/openssl.rs
io/src/io.rs
io/src/net/tcp.rs
postgres/Cargo.toml
server/Cargo.toml
test/Cargo.toml
tls/CHANGES.md
tls/Cargo.toml
tls/src/lib.rs
tls/src/openssl.rs
tls/src/rustls.rs

rework `xitca-client` and `xitca-http` to depend on `xitca-tls` for `rustls` and `opeensl` crate support.

add openssl feature.

---

client/Cargo.toml
client/src/client.rs
client/src/error.rs
client/src/lib.rs
client/src/request.rs
http-ws/CHANGES.md
http-ws/Cargo.toml
http-ws/src/lib.rs
test/Cargo.toml
test/tests/h1.rs
test/tests/h2.rs
test/tests/h2_v2.rs
test/tests/h3.rs
test/tests/websocket.rs

Majority of `Client`'s request api would not fail in place and error handling is delayed until `RequestBuilder::send` is called.

make request methods infallible.

---

client/Cargo.toml
client/src/client.rs
client/src/http_tunnel.rs
client/src/request.rs
client/src/tunnel.rs
client/src/ws.rs
test/Cargo.toml
test/tests/macro.rs

update `xitca-client` to use unreleased version of `xitca-http` 0.7.
remove `TunnelRequest` type and related type alias will point to `RequestBuilder`.

update xitca-client dep. dedup of RequestBuilder types.

---

postgres/src/cancel.rs
postgres/src/client.rs
postgres/src/column.rs
postgres/src/driver.rs
postgres/src/from_sql.rs
postgres/src/iter.rs
postgres/src/lib.rs
postgres/src/pipeline.rs
postgres/src/pool.rs
postgres/src/prepare.rs
postgres/src/query.rs
postgres/src/query/base.rs
postgres/src/query/encode.rs
postgres/src/query/simple.rs
postgres/src/row/traits.rs
postgres/src/row/types.rs
postgres/src/statement.rs
postgres/src/transaction.rs
postgres/src/types.rs

`BorrowToSql, FromSql, ToSql, Type` have been moved to `types` module

refactor encoding functions

---

client/src/h2/proto/dispatcher.rs
client/src/h3/proto/dispatcher.rs
test/tests/h2.rs
test/tests/h3.rs

Hey,
I was playing a bit with the client, and it seems that it has the same bug as the client from actix-web https://github.com/actix/actix-web/issues/3495 where having an host header on nginx will cause a 400.
This header is not used when on http2/http3 since it use the pseudo authority header, so i removed it in both cases to avoid this problem (don't know if nginx will have the same problem with http3, but at least it prevent it and should be harmless)

fix(client): remove host header on http2 / http3

---

.github/workflows/clippy-fmt.yml
http/src/h2/proto/hpack/encoder.rs
http/src/tls/openssl.rs

This should make ci green again, i was waiting on https://github.com/rust-lang/rust-clippy/pull/13953 to be merge but it seems this will take longer than expected to have it working,

chore(clippy): fix clippy errors

---

client/src/body.rs
client/src/connection.rs
client/src/h1/body.rs
client/src/http_tunnel.rs
client/src/ws.rs
test/tests/h1.rs

Pr is not finished, i only added a test.
Actually if a body is not readed on the client, but the reponse is dropped, conn will go back to the pool with existing data of the response not consumed, which will fail the next request since it will try to decode the header on the previous response body
This may happens if a client send a request, gets an error with a status code and a message in the body by example, and when there is a specific status code (in this case the error), will not bother to consume the body.
Not sure how to handle this well, i assume we should force the body to be consumed before going back to the pool but i'm not sure how to do this

fix(client): drop connection if body of a response was not consumed, to avoid bad state

---

web/Cargo.toml
web/src/server.rs

Maybe i miss something but actually binding web to h3 require a lot of boilerplate, this pr allow simplify this by adding a bind_h3 method to the app.
Since it need a QuicConfig i'm wondering if we should add a reexport for the QuicConfig (but can be done later)

feat(web): allow to bind h3 on web app

---

client/src/client.rs
client/src/http_tunnel.rs
client/src/lib.rs
client/src/request.rs
client/src/upgrade.rs

This PR allow a user to upgrade an HTTP request (only on http1 feature since it's not allowed on other protocol)
It's very similar to the connect api, it just have different check (add a special header for connection and check the switching protocl status code), i also added the headers to the response (since it can be needed to know on which protocol you have to upgrade).

feat(client): add support for upgrade request

---

client/src/builder.rs
client/src/middleware/async_fn.rs
client/src/middleware/mod.rs
client/src/service/async_fn.rs
client/src/service/http.rs
client/src/service/mod.rs

Ref https://github.com/HFQR/xitca-web/pull/1181
This PR allow an user to pass a closure as a middleware.

feat(client): allow to add a closure as a middleware in client

---

io/src/net.rs
server/src/builder.rs
server/src/net/mod.rs
server/src/server/mod.rs
server/src/server/service.rs
server/src/worker/mod.rs

Ref https://github.com/HFQR/xitca-web/issues/1190
See this comment : https://github.com/HFQR/xitca-web/issues/1190#issuecomment-2681544839
This allow end user to create its own listener as long as it returns a `xitca_io::net::stream` 
I did not make stream generic (could be in the future) neither.
Compared to the comment i choose to not make the Listen type generic, it could be in the future with another PR
In draft for the moment as i want to test this change on my project to be sure that i achieve what i want (getting back listener after shutdown)

feat(server): allow custom implementations of listener

---

io/src/net/quic.rs

This allow to create QuicListener when you don't want to use the builder.
Mainly this is because i have an already udp socket already binded and want to use it for the quic protocol instead of binding a new one (when transfering ownership of socket between process), see https://github.com/HFQR/xitca-web/issues/1190 for more context

feat(io): expose quic listener to be build from third party lib

---

http/src/http.rs

By default response version will be "1.1" , this fix ensure that we have the same version as the request for a response by default, it's required when some middleware may need to do various check depending on the response version ref https://github.com/HFQR/xitca-web/pull/1240

fix(http): when transforming a request to response keep the same http version
